spring:
  application:
    name: product-server
  security:
    user:
      name: admin
      password: select111***
  messages:
    basename: i18n/messages
    encoding: UTF-8
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    prefer-ip-address: true
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8500/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8520
  tomcat:
    uri-encoding: UTF-8
info:
  name: 'product-server'
  description: 'Parent pom providing dependency and plugin management for applications
		built with Maven'
  version: '1.0-SNAPSHOT'
  spring-boot-version: '2.0.4.RELEASE'
  spring-cloud-version: 'Finchley.SR1'